### ISSUE TITLE
mouse selection

### ISSUE THREAD

**Issue by ericlangedijk** [bonecode/BCEditor#15]
It seems mouse selection is going wrong.
Where there recent changes with this?
I am using your the BCEditor in a program of mine... Stability is a bit important if possible.

**Comment by NilsHoyer** [comment]
I found a problem with backwards selection - I've fixed it and commited the change.

I agree with you: It's very important to have stability. But there are very many problems inside BCEditor. I try to solve them one by one. But often, I decide to realize a bigger change. While doing this, I made mistakes, since I'm not perfect.

How should I handle this? Should I stop to modify BCEditor? How should I try to improve it, if I should not modify it?

I agree with you: I would like to be better. I would like not to make so many mistakes. But I endeaver me very much. Unfortunately, I'm not better like I am. How should I handle this?

**Comment by ericlangedijk** [comment]
Only commit changes after some testing?
I really like your component. You seem a good programmer.
Indeed versioning is difficult...
I'll try and download the latest now.

**Comment by NilsHoyer** [comment]
I didn't developed the BCEditor - Lasse did this, but he gave up this project. No I endeaver to complete his work.

And I agree with you: Testing is not my best work... 😢

**Comment by ericlangedijk** [comment]
I will have a look at it. It's interesting.
