### ISSUE TITLE
No need for separate Delphi/C++ builder bpl's

### ISSUE THREAD

**Issue by tonyt73** [bonecode/BCEditor#22]
I noticed that there was a commit that changed the name of the bpl's to include the compiler name.
This is not recommended as the resultant bpl should be the same regardless if Delphi or C++ Builder built it.
So the name should be Compiler agnostic. The previous naming scheme was fine. If a little verbose.
The new naming should/could include the platform though.
For example: BCEditor.Win32.bpl and BCEditor.Win64.bpl and BCEditor.design.Win32.bpl
I would also suggest that all output folders should be the same. That is no platform and no config.
For example: ..\BCEditor\VCL
This means that when you rebuild the packages for testing purposes and re-install in Rad Studio; RS will pick up the latest built version. Whether debug or release.
It also makes finding the correct BPL for installers a lot easier.

I can work on this if you like.

**Comment by NilsHoyer** [comment]
To compile the runtime package for C++Builder, we need the .cpp file - and the .pas file. If both have the same name, the compiler works fine. But the linker tries to implement to different .obj files - filename.obj and filename_0.obj. But the compiler didn't generate the filename_0.obj file. And because of this, the linker can't build the .bpl file.

I would be happy, if you would find a solution for this: I would like to have the same package name for Delphi and C++Builder. But I'm a Delphi developer. For me it's very hard to work with C++.

Btw: I can't compile the runtime page for 64 bit with C++Builder:

<pre>[ilink64 Error] Fatal: Unable to open file 'C0PKG64.O'</pre>

Can you compile it for 64 bit?

**Comment by tonyt73** [comment]
I will look into it.
I can compile 64 bit.

**Comment by tonyt73** [comment]
I added a PR for this issue.
https://github.com/bonecode/BCEditor/pull/23
I only have the Berlin Rad Studio (Delphi/C++)
So the Seattle project files are untested.

**Comment by tonyt73** [comment]
You are also better off getting Delphi to build the packages.
DCC64 is much better then the new Clang 64 bit C++ compiler.
I would suggest that we include a binaries package that includes the Delphi 32 runtime/design time BPLs and the 64 bit runtime BPL; with the appropriate Win32 C++ include/lib files.

**Comment by NilsHoyer** [comment]
I like small solutions, but you try to make big changes.

... and I still don't understand, why you do this.

Ok, I understood there are problems with nested declarations for the C++Builder. So in the moment, I try to understand why and if there is any way to keep them. If I don't find a solution for it (within one or two days), I will push out all nested declarations to the main level. Maybe you have some patience to wait for me?

**Comment by tonyt73** [comment]
I too would like a solution to the nested decl issue.
But the current change only addresses that in the short term.
Happy to wait for a solution and I will look for a solution too.
I can remove the nested decl change from this PR if you like.
The component will still work if built using Delphi.

It's your project; and I understand the changes are large.
But they are only project files and not everyone that will use the editor will have the same compiler.
Anyone on an older compiler than Seattle will not be able to load the projects files.
But it's your choice. Not trying to force anything changes on you; that you don't approve of.
Just trying to make it easier for anyone else with a different version of Rad Studio to use the project.

**Comment by tonyt73** [comment]
You can simply checkout my forked branch and try the changes for yourself.

**Comment by NilsHoyer** [comment]
First of all: The BCEditor is **not** my project. I just use it inside an other application, I clean it up and I try to support it. That's all. You are invited to do the same.

God overgave this project to me. So I try to handle this responibility by choosing, what I change and which pullrequests of other people I merge. I would be happy, to overgive this project to an other one. But before I do this, I want to believe he / she is able to handle this project as well.

I'm a Delphi developer - not a C++Builder professional. So I wish to get assistance from other people for the C++Builder problems. If you are able to handle them and I think you are able to do this, I would be happy to merge your modifications into this project.

But to trust you, I need more notes, that you know what you are doing and I have to believe your modification are useful for other people. Until now I'm not sure, if you are able to do this as well. Because of this, I asked you several times to show it to me.

Currently, I'm able to compile (and link) the BCEditor with C++Builder XE4 for 32 bit as well. Why do you tell me, I would not be able to do this? (I'm using an older compiler than Seattle.)

I really happy about any assistance to the BCEditor project. But god pleased me to decide which modifications are good and which are not helpful. So you have to show it to me. After I saw sometimes, your modifications are good, I will not longer ask you to descibe this to me. But until now, you offer very many changes - and I don't understand the sense of it. And if I ask you to describe that to me, you don't answer my question. I'm sorry, but if you don't help me to trust you, I will not overtake your modification. I would be happy, if you would understand this.

**Comment by tonyt73** [comment]
You also need to learn to supply proper comments when you submit code changes.
If you worked on my team; that kind of development behaviour would not last.
You need to get a little more maturity to your development.
Maybe you can ask God for help?
