### ISSUE TITLE
Why was the minimap removed?

### ISSUE THREAD

**Issue by tonyt73** [bonecode/BCEditor#24]
I loved this feature and its really handy in a modern editor these days.
Any chance the minimap could be returned?

**Comment by NilsHoyer** [comment]
I removed the mimimap, because it was very bad implemented: Bad code and very slow.

Currently, I renew the whole text drawing section. While this, I try to keep in my mind, there are wishes about a mimimap.

But I don't understand the sense of it: If the text is small, I don't need a mimimap. And if the text is hughe, it takes too much time to draw the mimimap.

Nevertheless: If there are more people, who which to have this feature, maybe somebody can bring it back - after I renewed the text drawing...

**Comment by tonyt73** [comment]
It is a good feature because it allows you to easily identify a section of code to jump to.
If I continue to use this project in my new project I will hopefully come back to work on the mini-map.
