### ISSUE TITLE
What is SyncEdit and how do you use it?

### ISSUE THREAD

**Issue by tonyt73** [bonecode/BCEditor#25]
Actually could you please explain all the listed features of BCEditor.
A syntax highlighting edit control for the RAD Studio (Delphi and C++ Builder VCL) **completion proposal**, **matching pair**, _minimap (no longer available) or is it?_, **sync edit**, **multi-caret editing**
Please explain each of the bold features.
Thank you.

**Comment by NilsHoyer** [comment]
I don't know all the features: Lasse developed the BCEditor - not I. Several weeks before, he gave up this project, dropped the GitHub account with the repository in it. Since I love this project, I reactivated the bonecode account and filled the repositioy again with his work. Up from that point, I try to cleanup the code, fix bugs and support the wishes of other people. And I still hope, other people support this project too.

The Completition Proposal works fine for me. The Matching Pairs too.

With the completion proposal features, you can press <Alt+Space> and you get a popup window with a list of words (text parts), which are senseful to insert at this position. But you have to fill that list by your own for your users. It depends on text, you show inside the BCEditor. I offer a tool for SQL in my other project. So I developed a SQL Parser, which knows on every text position, which are possible words for this position. For example, a list of all table names inside a SELECT query.

I'm not sure, but I believe you can mark (select) a text part and click to the SyncEdit icon in the bookmark area of the left margin. In that mode, you can move the caret (text cursor) to a word, which occurs several time inside the marked text. If you modify this word, all similar words will be modified too. For this, you see on each of that word a caret.

... please keep in your mind: I didn't develop this project and I support and other software project too. Inside that software, I'm using the BCEditor for a small text area. So I don't use extended features like minimap or multi carets.
