### ISSUE TITLE
Cyrillic symbols not highlighted

### ISSUE THREAD

**Issue by trash11** [bonecode/BCEditor#33]
Russian cyrillic symbols not highlighted, only english. Why? How to fix it?

**Comment by NilsHoyer** [comment]
Which highlighter do you use? Why highlighting do you expect? Do you have an example or a procedure how I can reproduce this issue?

**Comment by trash11** [comment]
@NilsHoyer, any highlighter. For example, add "тест" into reserve words group and try it

**Comment by trash11** [comment]
here is an example
[PBCoding_test.zip](https://github.com/bonecode/BCEditor/files/1033618/PBCoding_test.zip)

**Comment by trash11** [comment]
Here is an example:
[PBCoding_test.zip](https://github.com/bonecode/BCEditor/files/1033622/PBCoding_test.zip)

**Comment by NilsHoyer** [comment]
First of all: I'm not the initial developer of the BCEditor - I overtook this project 3 month ago. With the highlighter, I didn't work until now.

Your highlighter file is stored as a Ansi file - it will be loaded by using your local codepage. Since I use a german Windows system, your file will not be loaded as well on my end. But you can store it with UTF-8 encoding with a BOM. In that case, your file will be loaded as well on my system.

But there is a big problem inside BCEditor (BCEditor.Highlighter.pad, Line 2719): Only tokens starting with a Unicode below Chr(256) will be parsed - so currently, the BCEditor does not allow cyrillic keywords in the moment.

But this is not the whole problem: "abcа" of your highlighter will also not highlighted - until now, I don't know why. But "hello" will be highlighted. Strange...

So once again: I didn't develop the BCEditor - I don't know, why there are this limitations. Maybe because of speeding. Maybe...

Lasse (the initial developer of the BCEditor) is currently on a world traveling - we can't contact him. But before he started his traveling, he gave up the BCEditor project. I don't believe he will provide this project furter more after he's back. 

Why do you want to use cyrillic symbols in highlighted keywords?

**Comment by trash11** [comment]
> But this is not the whole problem: "abcа" of your highlighter will also not highlighted - until now, I don't know why. But "hello" will be highlighted. Strange...

Because the last `a` character is cyrillic.

> Why do you want to use cyrillic symbols in highlighted keywords?

I want to use russian language in a pseudo-code programming, just wonder

**Comment by NilsHoyer** [comment]
I don't believe, I will work on this issue with the next 2 month. (If I find a solution later on, I don't know.)
