### ISSUE TITLE
Cannot compile when generating C++Builder files (10.2.1 Tokyo)

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/BCEditor#45]
After telling the Delphi compiler to generate all C++Builder files, I get this error when building BCEditor.Delphi.Runtime.bpl:

[dcc32 Fatal Error] BCEditor.Delphi.Runtime.dpk(3): E2280 Unterminated conditional directive

For this line:
{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}

**Comment by NilsHoyer** [comment]
Strange, this message. The conditional directive is closed in line 26:
{$ENDIF IMPLICITBUILDING}

Can you find a solution by yourself, ... or do I have to install C++Builder 10.2 to find a solution for you?

**Comment by NilsHoyer** [comment]
The problem occurs on my end, if I make a change of the Runtime Package. Seems, there is a bug inside the Rad Studio, if there is no `{$R *.res}` directive inside the .dpk file. I removed that directive, because I don't want to offer an empty .res file.

Please take a look to your .dpk file and fix the problem in it or restore it from the reposity.
