### ISSUE TITLE
What's going on with BCEditor?

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/BCEditor#46]
Is anyone supporting BCEditor anymore? What happened to Lasse?

What happened to most of the pas source files like BCEditor.Print.pas and many more? I am trying to upgrade from a previous version that has a lot more source files.

Thanks.

**Comment by NilsHoyer** [comment]
Lasse gave up this project by himself - now, I'm working on it sometimes. But currently, I spend some holyda<s.

I cleaned up the code of Lasse. Several files, I summarized. But I removed a lot of features comepletely too. Some of them were implemented badly from Lasse, other features are not important from my point of view. I try to offer a small, easy to understand code.

Do you really use the print feature, or do you just want to have it?

**Comment by AlbertWiersch** [comment]
Hello,

Thanks for the response.

I was looking for a component to replace LMD SyntaxEdit which is used as the main editor in my product CSE HTML Validator, so the main editor would most likely need to have a print function or I'm sure some users would complain.

I really like some of the features I saw in BCEditor but I may have to stick with SyntaxEdit because it works well enough and has print functionality and Addict spell checking support. I assume BCEditor does not have any spell checking support either.

I might be able to give up a few features of SyntaxEdit to gain a few features that BCEditor has but giving up print support and spell checking are two 'big' features that I don't think I could give up.

**Comment by NilsHoyer** [comment]
You didn't answer my question - so once again: Do you really use the Print feature, or do you only want to have it?

Addict spell checking is not free available. Right? So how should I implement it?

**Comment by AlbertWiersch** [comment]
Well I never used BCEditor as the primary editor in my product so printing through BCEditor was never used there.

But I can't recall the last time I printed from the primary editor either, but it is not really about me, it's about my customers and whether they need printing, and I suspect some of them do. However I suppose it's not a big issue because most users probably don't print... although I would hate to remove a feature in a new version that is suppose to have more features, not less.

The lack of live spelling is a bigger issue because I do use that a lot and it's very helpful. It's not a free product but they might give you a free license if it's to integrate support for it into BCEditor. You may want to ask if you are interested: http://addictivesoftware.com/support.htm

Unfortunately I can't even get the latest version of BCEditor into an empty VCL form in a new project as I get an error.

I think my best bet is to try using the TMS editor since I already pay for those components and continue to just use SyntaxEdit as my main editor because it works "well enough" even though it doesn't have some features I wish it had.

I'd love to use BCEditor if I could get it to work smoothly but in order to get to that point it would probably take a lot of time and I'd probably run into a lot of issues that would have to be fixed or addressed, and the fact that I use C++Builder instead of Delphi makes things harder.

**Comment by NilsHoyer** [comment]
I thought about your suggestion with spellchecking. I love that idea.

But how should it work?

If I have an HTML text, the spell checking should only check the content, but not the HTML code, I think. So the spell checker has to know HTML - and all other 70 languages, or BCEditor has to separate the programming code from the text to be checked. In Delphi, it makes only sense to check strings, for example.

Do you have an idea, how I could a spell checker?

**Comment by AlbertWiersch** [comment]
I'm glad you like the spell-checking idea... it's very useful!

I believe the Addict spell checker simply ignores HTML tags (but does not ignore words in HTML comments). In fact, in the Addict options there is an option to ignore 'Markup languages (HTML, XML, etc)'. 

Honestly, I'm not sure how it works exactly as I did not write the spell checking code, but the easiest thing to do would seem to be just to ignore markup and code.

If you want to see how it's done in CSE HTML Validator with SyntaxEdit and the Addict spell checker then you can send me a private message: https://www.htmlvalidator.com/contactus.php

**Comment by NilsHoyer** [comment]
In the meantime, I thought further more about spell checking: The BCEditor is allready able to figure out different content types for each highlighter.

So I could add an option to the highlighter definition (*.json) to tell the BCEditor, which part of the text has to be checked.

Until now, I didn't try to implement the addict checker. But after you told me it would be shareware, I have to find an other spell checker or I can only implement a gateway to the spell checker.

Since the BCEditor is able to figure out, which part of the text has to be checked, maybe I can use an other (free) spell checker: The BCEditor can separate the text into words. So it's only a spell checker needed, which can check words.

But it would  be nice to check the grammar too.

Do you know a (free) spell checker, which can also check grammar?

**Comment by AlbertWiersch** [comment]
Sorry, I don't know of any Delphi spelling components other than the one I mentioned. I have TMS components and there may be one in there but I haven't used it. I've used the Addict components for many years now.

Have you contacted Addictive Software to see if they could give you a license so you can integrate BCEditor with their spell checking component?

**Comment by NilsHoyer** [comment]
BCEditor is a open source project. I don't believe they will give a licence to it. Everybody on the whole world could use that license.

**Comment by NilsHoyer** [comment]
The problem with the spell and grammar checking is much bigger, than I thought. Maybe I have the html text `Hello <b>W</b>urld.` (see the "u" after "W") To check this, I would have to transform it to `Hello Wurld` before checking. And after correction to , I have to replace replace the text. But how?

I like the idea to implement this feature into the BCEditor. But I don't believe to do this in this year.

**Comment by AlbertWiersch** [comment]
"BCEditor is a open source project. I don't believe they will give a licence to it. Everybody on the whole world could use that license." - I don't mean a license to everybody, just you so you could include support for it in BCEditor. BCEditor should still be able to work whether the developer has Addict or not.

For `Hello <b>W</b>urld`, I would just ignore that issue... I would ignore grammar issues too. I don't think Addict is a grammar checker. I would leave those issues for future versions.

**Comment by NilsHoyer** [comment]
I think, this is the main difference between you and me: You like half-ready implemented features - and you wants to have a lot of them. I prefer to have some few features only - but they should be implemented as well.

**Comment by AlbertWiersch** [comment]
The problem is that if you wait for everything to be perfect and fully mature, then almost nothing would ever be released. Almost everything can be improved. Sometimes you have to take steps. However, I would not agree with releasing buggy code that doesn't work right or that crashes, but a feature that may be limited in the first release but that works and is useful is better than not having that feature at all.

**Comment by NilsHoyer** [comment]
I agree with you: The very most people are looking for very fast solutions and they don't want to wait. Additional, the very most pleople are offering very fast solutions.

... but that solutions are bad. I take the time for my work, I need to do my job well.

I agree with you: My current offer of BCEditor is very buggy. I'm sad about this. But I change VERY many things and I didn't test it as well. If you want to assist my work, I would be happy, if you would test it and tell the bugs to me. But I think you are one of the people, how only want to take something - and not support other people. I'm sorry, but for pleople like this, I don't test my software.

Btw: I spent more time about the spell checking. I found two solutions. One of them is the Addict toolbox. It sould work with all MEMO and RICHEDIT windows, if I'm right. BCEditor is not one of them, but it supports all EM_xxx messages of Windows. Maybe because of this, Addict can work with the BCEditor too. If you want, you can test it.

I believe not only the spell checker toolbox should work fine. Also it's very important, to have a lot of supported dictionaries (different languages). Until now, I didn't compare Addict and NHunspell for Delphi. NHunspell uses the dictionaries of OpenOffice, like Firefox and Thunderbird too. NHunspell for Delphi wasn't updated since a long time. Maybe that is not a good solution.

If I'm right, Addict and Nunspell doesn't support grammar checking - only word, by word. This is bad, but it makes it much easier for me to implement it. Maybe I sould support both of them, since the BCEditor should have a gateway to it only. (But not in this year.)

**Comment by AlbertWiersch** [comment]
I'm sorry for the delay.

I would like to help with BCEditor but unfortunately I just don't have the time. I think I'm going to have to continue using LMD SyntaxEdit because it works well enough. It's had a few issues that I've reported and LMD has mostly fixed, but it doesn't have some "modern" editing features that I'd really like to have, and switching editors is very time consuming because there's always a bunch of little issues that I run into and usually some big issues. I was also sorry to hear the BCEditor is very buggy,,, that just won't work for me.

Honestly I wish there was a very good commercial editor for Delphi/VCL that was supported, mature (mostly bug free), and reasonably priced, but I haven't found one. I would pay money for that.

**Comment by NilsHoyer** [comment]
You want to get a lot, but you don't want to pay a lot. This doesn't work.

**Comment by AlbertWiersch** [comment]
The price would have to be reasonable based on the value I would get out of it. Nobody wants to pay more than something is worth to them.

Which brings me to one of my rants... one of the reasons I think it is harder to sell software now is because almost everyone wants free stuff or very cheap stuff, thanks to how cheap apps on the iPhone store are (many are FREE)... plus so many services are free on the Internet. The world surely has changed!

**Comment by NilsHoyer** [comment]
Nobody wants to pay more ...

I pay the price, I think it's fair. And I offer all I have and I can serve for free. I never ask about money or something else.

But I agree with you: You are very selfish and you try to get an advantage in every minute. But not all people are like you.

**Comment by AlbertWiersch** [comment]
> But I agree with you: You are very selfish and you try to get an advantage in every minute. But not all people are like you.

Wow... where did I ever say that? I'm selfish because I don't want to pay too much for stuff? WOW! I'm outta here.
