### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Dimonka2** [bonecode/BCEditor#48]
Hi
Is there a list of recent changes in the editor? Is there any recommendation how to update application to the new version?
So far I found few properties that are gone or have changes in the name: DisplayCaretX/Y, TopLine, SelectedText, SelectionBeginPosition, SelectionEndPosition

**Comment by NilsHoyer** [comment]
Lasse (the initial developer of BCEditor) gave up this project at the begin of this year. I overtook the project and started to cleanup the project. While doing this, I renewed the VERY much of the editor. Some features, I removed, since I thought they are not sense ful. Other features, I removed, since they were implemented very bad.

But I try to bring that features back. For example, the Minimap is back since this days.

You can use `CaretPos` to know the position of the caret. It shows the position inside the whole text - not the position inside the display. (For WordWrap and CodeFolding, the position can be different.)

TopLine, I removed complete. Why do you want to have it?

With SelStart, SelLength and SelText, you can get the selection. With PosToCharIndex and CharIndexToPos you get the position inside the text. I changed this, to be more compatible to TMemo and TRichEdit controls.

Until now, I didn't wrote a documentation. I'm sorry about this. Please ask here, whatever you want. If you ask too much, I would write a documentation to protect me against you questions... ;-)

**Comment by Dimonka2** [comment]
> TopLine, I removed complete. Why do you want to have it?
Basically I use one editor for several files and I need to restore the document state while switching between files. TopLine was a part of the "restoration". Maybe you can suggest a better way to persist editor state?

**Comment by NilsHoyer** [comment]
> Basically I use one editor for several files and I need to restore
> the document state while switching between files.

Why don't you use several TBCEditor instances at once?

Currenty, by default TBCEditor uses DoubleBuffers. If you disable that 
feature, each TBCEditor instance don't need a lot of Memory, I think (if 
you load small files).

> TopLine was a part of the "restoration".

Is TopLine really a good solution? Or is TopRow a better solution? 
TopRow shows the row. If you use WordWrap, each line can have multiple rows.

I've implemented TopRow - without any test of it. If you want, you can 
test it and tell me, if it works.

Or you can use TextPos. That shows the position in Pixel. But I think, 
this is not a good solution for you.

If you think, TopLine would be better for you, pleas let me know why.
