### ISSUE TITLE
Not Working for Me

### ISSUE THREAD

**Issue by BW022** [bonecode/BCEditor#50]
No installation instructions. Even when the components were installed...

The demo immediately freezes when you click in the editor.
Attempting to use the unit in a new project generates a can't find BCEditor when you attempt to compile it.

**Comment by NilsHoyer** [comment]
> No installation instructions.

Do you wish the have a manual? I would like to have it too...

> The demo immediately freezes when you click in the editor.

Can you update my last changes, and let me know, if the problem still 
exists on you end? (Currently, this problem does not occur on my end. 
But other users reported, the whole program freezes often.)

> Attempting to use the unit in a new project generates a can't find 
> BCEditor when you attempt to compile it.

BCEditor us inside a newer update. In older updates, the BCEditor.Editor 
was used.

So I wonder, why you don't find BCEditor, since it should be inside the 
latest updates.
