### ISSUE TITLE
Copy/paste clipboard operation error

### ISSUE THREAD

**Issue by den-low** [bonecode/BCEditor#6]
The BCEditor do not paste content that have been copied from it. To reproduce error copy or cut any content from BCEditor and try to paste it. The content is copy but do not paste. I checked this error on demo and component under XE7.

**Comment by bonecode** [comment]
I'm sorry about the but - I've fixed them.

**Comment by NilsHoyer** [comment]
I'm sorry about the bug - I've fixed them.

**Comment by den-low** [comment]
Strange but the bug is already here. I've checked a procedure TBCBaseEditor.DoPasteFromClipboard; and ClipboardData := GlobalLock(Global); returns nil with ERROR_INVALID_HANDLE (0x6) error. May be better use Vcl.Clpbrd unit for clipboard operations?

**Comment by NilsHoyer** [comment]
... but `Vcl.Clipbrd` do the same inside `TClipboard.GetTextBuf`:

```Delphi
var
  Data: THandle;
begin
  Open;
  try
    Data := GetClipboardData(CTextFormat);
    if Data = 0 then
      Result := 0
    else
    begin
      Result := StrLen(StrLCopy(Buffer, GlobalLock(Data), BufSize - 1));
      GlobalUnlock(Data);
    end;
```

And I follow the [`GetClipboardData`](https://msdn.microsoft.com/de-de/library/windows/desktop/ms649016(v=vs.85).aspx#_win32_Pasting_Information_from_the_Clipboard) example from Microsoft:

```C++
        hglb = GetClipboardData(CF_TEXT); 
        if (hglb != NULL) 
        { 
            lptstr = GlobalLock(hglb); 
            if (lptstr != NULL) 
            { 
                // Call the application-defined ReplaceSelection 
                // function to insert the text and repaint the 
                // window. 
```

There is an issue in the documention of `GetClipboardData`: There is noware described, what kind of Handle is returned. But since the example of Microsoft and the `Vcl.Clipbrd` unit uses the same way like me, I don't have an idea, what I could change.

Are you sure, your clipboard has a `CF_UNICODETEXT` while you tried to paste? (Sorry about this question - I don't have any other idea...).

Does `GetClipboardData` returns a handle (value > 0) or does it fails?

**Comment by den-low** [comment]
I compare a vcl clipboard works and editor one and comment EmptyClipboard(); in DoCopyToClipboard and every work fine. Also a GlobalUnlock is missing for GlobalLock in DoCopyToClipboard.

**Comment by den-low** [comment]
Heh, another addition the GlobalFree do not need in DoCopyToClipboard. So need simply replace GlobalFree to GlobalUnlock and all work fine)

**Comment by NilsHoyer** [comment]
Thank you for your assistance - I applied your work.
