### ISSUE TITLE
Add syntax Transact SQL.Json and colors SMSS.Json 

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#72]
Newer versions of SQL server support some more operators.
I've updated Json's what comes with BCEditor to highlight new OPENJSON and OPENXML operators.
Also, added SMSS color scheme.
Not all operators highlighted, but there is some better new look i tihnk.

And BCEditor has Json's named 
SQL - Sybase.json
SQL - PostgreSQL.json
SQL - Oracle.json
But there is no JSON for Transact or MSSQL
Confusing a bit.

![screen](https://user-images.githubusercontent.com/34241725/44835077-a79e0880-ac3b-11e8-8ac9-f59c13307daf.png)
[SMSS - Color.txt](https://github.com/bonecode/BCEditor/files/2334973/SMSS.-.Color.txt)

[SQL - Transact SQL.txt](https://github.com/bonecode/BCEditor/files/2334961/SQL.-.Transact.SQL.txt)

**Comment by NilsHoyer** [comment]
I have a MySQL highlighter too. But it uses one more color (conditional MySQL code). Because of this, I didn't enclose the highlighter to the BCEditor probject. You can find it here:
https://github.com/NilsHoyer/MySQL-Front/tree/master/Source/BCEditor/Resource

The highlighters enclosed to the BCEditor project are using the different color files. If I enclose my MySQL or your Transact SQL highlighters, it will not look fine with the other color files.

I don't like non standard colors, but other people like them. So I don't not support them, but I still offer them.

**Comment by ValeriyTitov** [comment]
> I don't like non standard colors
Nobody does. 
Standart colors - it's same color scheme what user work with.

If i work with SSMS(Microsoft SQL Managment Studio) - i want SQL syntax to be highlighted same as in SSMS
C# - highlights same is as VisualStudio.
PL/SQL - same color as in Oracle

I couldnt find color/syntax scheme for Transact SQL and made it myself.
